[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité de base
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self'"
    
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
    
    # HSTS (HTTPS Strict Transport Security)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Cache Control pour les ressources statiques
    Cache-Control = "public, max-age=31536000, immutable"

# Headers spécifiques pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Headers pour les fichiers de données
[[headers]]
  for = "/datas/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

# Redirections
[[redirects]]
  from = "/fr"
  to = "/"
  status = 200

[[redirects]]
  from = "/en"
  to = "/"
  status = 200

# Gestion des erreurs 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers pour le service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Configuration PWA
[[headers]]
  for = "/manifest-*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"
